"""P4 — the Tranche-1 COARSE-NETTING immigrant/non-immigrant ownership RATIO.

THE QUESTION, precisely (spec §6): the coarse netting applies `p_imm(a) =
p_nonimm(a) × ratio`, where `ratio` is the **Census immigrant/non-immigrant
ownership RATIO at CMA level** (banded). Without it a new (rental-skewed)
immigrant reads as a new buyer and the ownership-flow inversion collapses — the
netting IS the showcase's originality claim, so a silent 1.0 is FORBIDDEN. This
probe sources that ratio and records it as a BANDED multiplier (point ± spread).

WHAT THE HUNT ESTABLISHED (recorded live below, so a re-run re-derives it):
there is NO free StatCan cube that publishes an immigrant/non-immigrant
ownership RATE at the Montréal/Québec CMA level. This is proven at the
DIMENSION level, not just by title:
  * Census (98*): NO cube crosses immigrant status × TENURE. The 98* cubes that
    carry an immigrant dimension (98100327 housing suitability, 98100328
    shelter-cost-to-income, 98100656 labour force) have NO tenure dimension; and
    NO 98* immigrant/period-of-immigration cube carries a tenure dimension.
  * CHSP (46*) is the only immigrant × home-ownership family, but it counts
    residential-property OWNERS (a numerator) — not owner households over total
    households — so it yields no ownership RATE; and its homeownership coverage
    EXCLUDES Québec (the CHSP gap), so the MTL/QC CMA cells do not exist there.

So the SPEC-SANCTIONED outcome (spec §6 "record a documented multiplier band
with `borrowed_prior` if the exact CMA cell is unavailable; NO silent 1.0") is a
documented fallback band, sourced from CITED published immigrant-vs-non-immigrant
homeownership figures, with the RATIO computed in code from those cited rates and
the whole thing flagged `borrowed_prior`.

ANTI-FABRICATION (the cardinal discipline): every figure below is either
  `cited`   — an external published rate, printed with its source + verbatim
              quote inline (the input homeownership rates), or
  `derived` — computed from those cited rates in THIS run (the ratios and the
              band endpoints).
No ratio is hand-typed. The `Fact` registry self-accounts for the mix, and the
note is GENERATED by running this script — never hand-edited.

WHY A BAND, NOT A POINT (recorded, not resolved here — a Task-15 finding): the
Tranche-1 arrival flow is dominated by RECENT immigrants, whose ownership is
rental-skewed; a POOLED all-immigrant ratio is ≥1 (established immigrants own at
native-or-higher rates) and would DEFEAT the netting. The band is built from the
recent-immigrant evidence; Task 15 declares the central value per the spec's
central-value rule (spec §"Run contract for banded assumptions"), and Tranche 2
replaces this coarse ratio with the years-since-landing S-curve.

Run:  cd demoflow && uv run python probes/run_p4.py
"""

import json
import urllib.request
from dataclasses import dataclass
from pathlib import Path

# --- WDS endpoints ----------------------------------------------------------
WDS_LIST = "https://www150.statcan.gc.ca/t1/wds/rest/getAllCubesListLite"
WDS_META = "https://www150.statcan.gc.ca/t1/wds/rest/getCubeMetadata"  # POST [{"productId": int}]
OUT = Path(__file__).resolve().parent / "P4-immigrant-ownership-diff.md"
TIMEOUT = 120
META_CHUNK = 30

# --- catalogue-sweep keys ---------------------------------------------------
# Title-level cross (immigrant AND tenure/ownership). Kept broad on purpose: the
# hunt must SHOW it searched, so a NOT-FOUND is credible.
IMM_TITLE_KW = ("immigrant", "immigration", "period of immigration", "place of birth",
                "generation status", "admission categor", "citizenship")
TEN_TITLE_KW = ("tenure", "owner", "ownership", "rent")
# Dimension-level audit families (98* Census only — the free source the spec wants).
HOUSING_TITLE_KW = ("tenure", "housing", "dwelling", "shelter", "condominium",
                    "core housing need", "maintainer", "household")

# Targeted candidates, each recorded so the note shows HOW it resolved.
PLAN_WRONG_PID = "98100279"          # the plan's guess — actually "grandparents in household"
IMM_HOUSING_NO_TENURE = ("98100327", "98100328")  # immigrant × housing, but NOT tenure
CHSP_OWNER_PID = "46100098"          # CHSP owners-numerator; excludes Québec

# --- the CITED fallback figures (external published rates) ------------------
# Source 1 — the dedicated recent-immigrant homeownership study. Its metric is an
# actual homeownership RATE (individuals aged 25-54 owning ≥1 residential
# property, over that group), and its population (recent immigrants) matches the
# netting's semantic target. Québec is NOT among its provinces (CHSP homeownership
# coverage excludes it) — that absence IS why the band is `borrowed_prior`.
SOURCE1 = {
    "catalogue": "46-28-0001",
    "title": "The homeownership trajectories of recent immigrants",
    "release": "2026-06-16",
    "url": "https://www150.statcan.gc.ca/n1/pub/46-28-0001/2026001/article/00002-eng.htm",
    "quote": ('"the homeownership rate for recent immigrants in the fifth year after '
              'admission rose from 35.7% in 2018 to 40.2% in 2021, while that for '
              'Canadian-born individuals fell from 50.7% to 47.8%" (Ontario) — Chart 1 '
              "reports the fifth-year vs Canadian-born rate for all seven covered provinces."),
}
# Chart 1, 2021, fifth year after admission: (recent-immigrant %, Canadian-born %).
# Verbatim from Source 1 (verified against the article table and the Daily release).
S1_YEAR5 = {
    "Prince Edward Island": (49.8, 52.5),
    "Nova Scotia": (48.1, 49.8),
    "New Brunswick": (56.6, 54.8),
    "Ontario": (40.2, 47.8),
    "Manitoba": (47.9, 50.0),
    "Alberta": (39.7, 51.9),
    "British Columbia": (37.5, 43.3),
}
# Earlier-tenure rows (year 1 and year 3), recorded so the recent-vs-settled
# tension is visible to Task 15 — NOT used for the recommended band.
S1_YEAR1 = {
    "Prince Edward Island": 10.5, "Nova Scotia": 11.5, "New Brunswick": 14.5,
    "Ontario": 7.4, "Manitoba": 13.4, "Alberta": 8.3, "British Columbia": 8.2,
}
S1_YEAR3 = {
    "Prince Edward Island": 35.9, "Nova Scotia": 33.5, "New Brunswick": 41.3,
    "Ontario": 24.9, "Manitoba": 32.0, "Alberta": 23.4, "British Columbia": 25.0,
}

# Source 2 — a DIFFERENT metric (owner-occupied dwellings maintained per 1,000
# people, all ages), used ONLY to record the pooled-vs-recent tension: pooled
# all-immigrant occupancy EXCEEDS Canadian-born, while recent (0-5yr) is far below.
SOURCE2 = {
    "catalogue": "36-28-0001",
    "title": "Housing use of immigrants and non-permanent residents in ownership and rental markets",
    "release": "2025-05-28",
    "url": "https://www150.statcan.gc.ca/n1/pub/36-28-0001/2025005/article/00003-eng.htm",
    "quote": ('"immigrants occupy, on average, 310 owned units ... per 1,000 people ..., '
              'compared with ... 271 owned units ... for Canadian-born individuals"; recent '
              'immigrants (0 to 5 years) occupy 115 owned units per 1,000.'),
}
S2_IMM_OWNED_PER_1000 = 310.0          # pooled, all immigrants
S2_CDNBORN_OWNED_PER_1000 = 271.0
S2_RECENT_OWNED_PER_1000 = 115.0       # recent immigrants, 0 to 5 years


# --- Fact provenance registry (reused verbatim from run_p3.py) --------------
_FACTS: list["Fact"] = []


@dataclass(frozen=True)
class Fact:
    """A narrative figure carrying HOW this run obtained it.

    `derived` — computed from a CITED rate in THIS run (it changes when the source
                data changes), naming its inputs; `cited` — external, printed with
                its citation inline. The header is assembled from the mix actually
                present, so it cannot drift from the body.

    Known weakness (unchanged from P3): `derived` does NOT verify the value was
    computed — the tag is author-chosen. So the discipline is enforced by CODE:
    every ratio/band below is a live arithmetic expression over the cited rates,
    not a literal handed to `Fact.derived`.
    """

    text: str
    kind: str  # "derived" | "cited"
    source: str

    def __post_init__(self) -> None:
        _FACTS.append(self)

    @classmethod
    def derived(cls, value: object, how: str) -> "Fact":
        return cls(f"{value}", "derived", how)

    @classmethod
    def cited(cls, value: object, source: str) -> "Fact":
        return cls(f"{value}", "cited", source)

    def __str__(self) -> str:
        return self.text if self.kind == "derived" else f"{self.text} [cited: {self.source}]"


def _provenance_header() -> list[str]:
    derived = [f for f in _FACTS if f.kind == "derived"]
    cited = [f for f in _FACTS if f.kind == "cited"]
    lines = [
        "Written by `probes/run_p4.py`; nothing in this file is hand-edited.",
        "",
        "The catalogue sweep and dimension-level audit in §1-§3 are generated from the live "
        "WDS responses of the run that wrote this file. The fallback band in §4 is computed "
        "from CITED published rates: the input homeownership rates are external (each printed "
        "with its source and a verbatim quote); every RATIO and band endpoint is computed in "
        "code from those rates — no ratio is hand-typed.",
    ]
    if _FACTS:
        lines.append(
            f"§4 tags its headline figures with provenance. This run registered {len(_FACTS)}: "
            f"{len(derived)} DERIVED (computed from the cited rates in this same run) and "
            f"{len(cited)} CITED (external published rates, printed with the citation inline). "
            f"Untagged numerals elsewhere are: §1-§3 audit metadata (product ids, dimension "
            f"labels, counts of what was checked); the cited source rates and figures shown in "
            f"the §4 tables and verbatim quotes (traceable to the named articles); reference "
            f"labels (census/horizon years, age ranges); and the per-row ratios and inline "
            f"ranges computed beside those cited rates."
        )
    if cited:
        lines += ["", "Externally cited figures:"]
        lines += [f"- {f.text} — {f.source}" for f in cited]
    lines.append("")
    return lines


# --- helpers reused from run_p3.py ------------------------------------------
def _table_number(pid: object) -> str:
    """`98100231` -> `98-10-0231-01`, StatCan's published table-number form."""
    p = str(pid)
    if len(p) != 8 or not p.isdigit():
        raise ValueError(f"unexpected productId shape {pid!r}; cannot derive a table number")
    return f"{p[0:2]}-{p[2:4]}-{p[4:8]}-01"


def _table_url(pid: object) -> str:
    return f"https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid={pid}01"


def _post(url: str, payload: list) -> list:
    req = urllib.request.Request(
        url, data=json.dumps(payload).encode(), headers={"Content-Type": "application/json"}
    )
    return json.loads(urllib.request.urlopen(req, timeout=TIMEOUT).read())


# --- live hunt --------------------------------------------------------------
def _catalogue() -> list[dict]:
    raw = urllib.request.urlopen(WDS_LIST, timeout=TIMEOUT).read()
    return json.loads(raw)


def _title_cross_hits(cubes: list[dict]) -> list[tuple[str, str]]:
    """Cubes whose TITLE mentions immigrant AND tenure/ownership (any family)."""
    hits = []
    for c in cubes:
        pid = str(c.get("productId") or "")
        t = c.get("cubeTitleEn") or ""
        tl = t.lower()
        if any(k in tl for k in IMM_TITLE_KW) and any(k in tl for k in TEN_TITLE_KW):
            hits.append((pid, t))
    return sorted(set(hits))


def _meta_batch(pids: list[str]) -> dict[str, dict]:
    """Fetch metadata for many productIds; returns {pid: object}. Batched POST."""
    out: dict[str, dict] = {}
    for i in range(0, len(pids), META_CHUNK):
        batch = [{"productId": int(p)} for p in pids[i : i + META_CHUNK]]
        for r in _post(WDS_META, batch):
            obj = r.get("object") or {}
            pid = str(obj.get("productId") or "")
            if pid:
                out[pid] = obj
    return out


def _dim_names(obj: dict) -> list[str]:
    return [(d.get("dimensionNameEn") or "") for d in obj.get("dimension", []) or []]


def _immigrant_dims(obj: dict) -> list[str]:
    return [n for n in _dim_names(obj)
            if "immigrant" in n.lower() or "immigration" in n.lower()]


def _tenure_dims(obj: dict) -> list[str]:
    hits = []
    for d in obj.get("dimension", []) or []:
        n = (d.get("dimensionNameEn") or "").lower()
        members = [(m.get("memberNameEn") or "").lower() for m in d.get("member", [])]
        if "tenure" in n or any(("owner" in m or "renter" in m) for m in members):
            hits.append(d.get("dimensionNameEn"))
    return hits


def _geo_members(obj: dict) -> list[str]:
    for d in obj.get("dimension", []) or []:
        if (d.get("dimensionNameEn") or "").lower().startswith("geo"):
            return [(m.get("memberNameEn") or "") for m in d.get("member", [])]
    return []


class VacuousAuditError(RuntimeError):
    """A NOT-FOUND must be EARNED. Raised when the WDS answered but with an empty
    population (200 -> [] / {}), so no audit actually ran over it. Routes to
    UNCONFIRMED-PROBE-FAILED rather than laundering a vacuous response into a false
    NOT-FOUND (NS #1: a verification gate must REFUSE when it cannot verify — an
    empty response is 'unknown', never 'absent')."""


def _guard_audit_ran(cubes: list, families: list, meta: dict, cand_meta: dict) -> None:
    """Floor guard: RAISE (-> UNCONFIRMED) on any vacuous audit input, so a
    NOT-FOUND is honored only over an audit that actually ran on a non-empty
    population. Kept a standalone function so it can be mutation-tested."""
    if not cubes:
        raise VacuousAuditError("getAllCubesListLite returned an empty catalogue")
    if families and not meta:
        raise VacuousAuditError(
            "the metadata probe resolved 0 cubes though the candidate families were non-empty"
        )
    if not cand_meta:
        raise VacuousAuditError("the targeted candidate probe resolved 0 cubes")


def _hunt(note: list[str]) -> str:
    """Run the live hunt, append its record to `note`, return the verdict token.

    Verdict is one of:
      NOT-FOUND-AT-CMA          — audited: no free cube yields the CMA ratio.
      UNCONFIRMED-PROBE-FAILED  — the WDS did not answer; the audit could not run.
    The fallback band in §4 does NOT depend on this — it is external published
    literature — so an outage cannot suppress the deliverable, only the audit.
    """
    # --- §1 catalogue sweep (title-level) -----------------------------------
    note += ["## 1. Catalogue sweep — title-level immigrant × tenure cross", ""]
    cubes = _catalogue()
    cross = _title_cross_hits(cubes)
    note.append(f"- `getAllCubesListLite` -> {len(cubes)} cubes in catalogue.")
    note.append(f"- Titles mentioning immigrant/origin AND tenure/owner/rent ({len(cross)}):")
    for pid, t in cross:
        note.append(f"  - `{pid}` {t}")
    # Breakdown by product-family prefix, DERIVED from the live hits so the enumeration
    # accounts for ALL of them (not a hand-typed family list that can miss a hit).
    by_prefix = {p: sum(1 for pid, _ in cross if pid.startswith(p))
                 for p in sorted({pid[:2] for pid, _ in cross})}
    note += [
        "",
        f"Breakdown of the {len(cross)} hits by product-family prefix: {by_prefix}. None is a "
        "free Census immigrant × TENURE cross-tab: the `33` rows count enterprise OWNERS; the "
        "`46` rows are CHSP residential-property OWNERS (a numerator, not a rate; homeownership "
        "coverage excludes Québec); the rest matched a tenure keyword only as a TITLE SUBSTRING "
        "and are NOT about housing tenure — e.g. `37100127` on app-RENT-ices (apprentices) and "
        "the `98` pair on pa-RENT-s' (parents') citizenship. Title search alone cannot prove "
        "absence, so §2 audits at the DIMENSION level.",
        "",
    ]

    # --- §2 dimension-level audit (the auditable NOT-FOUND) ------------------
    note += ["## 2. Dimension-level audit — the auditable NOT-FOUND", ""]
    housing_pids = sorted({
        str(c.get("productId")) for c in cubes
        if str(c.get("productId") or "").startswith("98")
        and any(k in (c.get("cubeTitleEn") or "").lower() for k in HOUSING_TITLE_KW)
    })
    imm_pids = sorted({
        str(c.get("productId")) for c in cubes
        if str(c.get("productId") or "").startswith("98")
        and any(k in (c.get("cubeTitleEn") or "").lower() for k in IMM_TITLE_KW)
    })
    meta = _meta_batch(sorted(set(housing_pids) | set(imm_pids)))

    # Direction A: 98* housing cubes carrying an immigrant dimension.
    a_hits = []
    for pid in housing_pids:
        obj = meta.get(pid)
        if obj and _immigrant_dims(obj):
            a_hits.append((pid, obj))
    # Direction B: 98* immigrant cubes carrying a tenure dimension.
    b_hits = [(pid, meta[pid]) for pid in imm_pids
              if meta.get(pid) and _tenure_dims(meta[pid])]

    note += [
        f"Probed metadata for {len(meta)} distinct 98* cubes "
        f"({len(housing_pids)} housing-family, {len(imm_pids)} immigrant-family).",
        "",
        "**Direction A — 98* housing/dwelling/tenure/maintainer cubes carrying an "
        "IMMIGRANT dimension:**",
    ]
    for pid, obj in a_hits:
        ten = _tenure_dims(obj)
        note.append(
            f"  - `{pid}` {obj.get('cubeTitleEn')} — immigrant dim {_immigrant_dims(obj)}; "
            f"tenure dim {ten or 'NONE'}"
        )
    a_with_tenure = [pid for pid, obj in a_hits if _tenure_dims(obj)]
    note += [
        f"  -> {len(a_hits)} carry an immigrant dimension; {len(a_with_tenure)} of those ALSO "
        f"carry a tenure dimension. (Housing suitability, shelter-cost-to-income and labour "
        f"force are NOT tenure.)",
        "",
        "**Direction B — 98* immigrant/period-of-immigration cubes carrying a TENURE "
        "dimension:**",
        f"  -> {len(b_hits)} of {len(imm_pids)} immigrant cubes carry a tenure dimension: "
        f"`{[p for p, _ in b_hits]}`.",
        "",
    ]
    census_cross_exists = bool(a_with_tenure or b_hits)

    # --- §3 targeted candidate probe (plan's wrong id + near-misses) --------
    note += ["## 3. Targeted candidates — how each resolves", ""]
    cand_meta = _meta_batch([PLAN_WRONG_PID, *IMM_HOUSING_NO_TENURE, CHSP_OWNER_PID])

    plan_obj = cand_meta.get(PLAN_WRONG_PID, {})
    note.append(
        f"- **{PLAN_WRONG_PID}** (the plan's product id) resolves to "
        f"**\"{plan_obj.get('cubeTitleEn', '?')}\"** — dimensions "
        f"{_dim_names(plan_obj)}. Nothing to do with immigrant status or tenure; a plan-author "
        f"guess (same class as P3's candidates)."
    )
    for pid in IMM_HOUSING_NO_TENURE:
        obj = cand_meta.get(pid, {})
        note.append(
            f"- **{pid}** \"{obj.get('cubeTitleEn', '?')}\" — HAS an immigrant dimension "
            f"{_immigrant_dims(obj)} at CMA geography, but its housing axis is "
            f"{[n for n in _dim_names(obj) if n not in _immigrant_dims(obj)][-2:]}, NOT tenure "
            f"(owner/renter). No ownership rate derivable."
        )
    chsp = cand_meta.get(CHSP_OWNER_PID, {})
    chsp_geo = _geo_members(chsp)
    chsp_qc = [m for m in chsp_geo if m and ("Que." in m or "Québec" in m or "Quebec" in m)]
    note.append(
        f"- **{CHSP_OWNER_PID}** \"{chsp.get('cubeTitleEn', '?')}\" (CHSP) — dimensions "
        f"{_dim_names(chsp)}. It counts property OWNERS by immigration status (a numerator), "
        f"NOT owner households over total households, so it yields no ownership RATE; its "
        f"'Proportion of owners by immigration status' estimate is the owner-pool COMPOSITION, "
        f"not owners/population. Its {len(chsp_geo)} geographies include "
        f"{len(chsp_qc)} Québec-named members -> the Montréal/Québec CMA cells are absent "
        f"(the CHSP homeownership coverage gap)."
    )
    note.append("")

    # FLOOR GUARD (NS #1 — a verification gate must REFUSE when it cannot verify): a
    # WDS-up-but-EMPTY response (200 -> [] / {}) does NOT raise, so without this a
    # vacuous audit would launder straight into a false NOT-FOUND over a population of
    # zero. RAISE instead -> main routes it to UNCONFIRMED-PROBE-FAILED. A NOT-FOUND is
    # honored ONLY over an audit that actually ran on a non-empty population.
    _guard_audit_ran(cubes, sorted(set(housing_pids) | set(imm_pids)), meta, cand_meta)

    verdict = "NOT-FOUND-AT-CMA" if not census_cross_exists else "FOUND-CANDIDATE"
    if census_cross_exists:
        # A structural surprise: some cube DOES cross immigrant × tenure. Record it
        # loudly rather than silently proceeding to the fallback. (Kept auditable.)
        note += [
            "> UNEXPECTED: the dimension audit found a cube crossing immigrant status × "
            "tenure. This contradicts the recorded premise; the fallback band below is NOT a "
            "substitute for pulling that cube. See Direction A/B hits above. This probe records "
            "the surprise and does NOT invent a NOT-FOUND.",
            "",
        ]
    note += [
        f"## LIVE HUNT VERDICT: {verdict}",
        "",
        "No free StatCan cube publishes an immigrant/non-immigrant ownership RATE at the "
        "Montréal/Québec CMA level: §2 dimension-audited the title-selected candidate pool "
        "(every 98* cube whose title carries a housing OR an immigrant term — both directions) "
        "and found no immigrant × tenure cross. That title-selected pool is where such a cube "
        "MUST surface: under StatCan's naming a genuine immigrant×tenure cross-tab would carry "
        "an immigrant or a housing term in its title, so the residual reliance on title-"
        "selection is bounded, not exhaustive coverage of all 98* cubes. CHSP (`46*`) is an "
        "owners-numerator that excludes Québec (§3). Therefore the spec §6 documented-fallback "
        "path applies.",
        "",
    ]
    return verdict


# --- fallback band (CITED rates -> DERIVED ratio, network-independent) ------
def _fallback_band(note: list[str]) -> tuple[float, ...]:
    """Compute the bands from the cited rates.

    Returns (lo, center, hi, lo3, ctr3, hi3, combined_lo, combined_hi): the
    recommended fifth-year cross-provincial band, the year-3 tenure-anchor band
    (the dominant axis), and the full plausible range across all three tenure
    anchors (year 1/3/5) × geography.
    """
    ratios = {prov: rec / cdn for prov, (rec, cdn) in S1_YEAR5.items()}
    lo = min(ratios.values())
    hi = max(ratios.values())
    center = sum(ratios.values()) / len(ratios)
    lo_prov = min(ratios, key=ratios.get)
    hi_prov = max(ratios, key=ratios.get)

    pooled_ratio = S2_IMM_OWNED_PER_1000 / S2_CDNBORN_OWNED_PER_1000
    recent_ratio = S2_RECENT_OWNED_PER_1000 / S2_CDNBORN_OWNED_PER_1000

    # Register provenance: the studies are CITED; the band + illustration are DERIVED.
    Fact.cited(
        f"recent-immigrant vs Canadian-born fifth-year homeownership rates, 7 provinces "
        f"(e.g. Ontario 40.2% vs 47.8%)",
        f"Statistics Canada, catalogue {SOURCE1['catalogue']}, \"{SOURCE1['title']}\", "
        f"Chart 1, released {SOURCE1['release']}. {SOURCE1['url']}",
    )
    Fact.cited(
        f"owned units per 1,000 people: immigrants {S2_IMM_OWNED_PER_1000:.0f} (pooled) / "
        f"{S2_RECENT_OWNED_PER_1000:.0f} (recent 0-5yr) vs Canadian-born "
        f"{S2_CDNBORN_OWNED_PER_1000:.0f}",
        f"Statistics Canada, catalogue {SOURCE2['catalogue']}, \"{SOURCE2['title']}\", "
        f"released {SOURCE2['release']}. {SOURCE2['url']}",
    )
    f_lo = Fact.derived(f"{lo:.3f}", f"min province ratio ({lo_prov}: "
                        f"{S1_YEAR5[lo_prov][0]}/{S1_YEAR5[lo_prov][1]})")
    f_ctr = Fact.derived(f"{center:.3f}", "unweighted mean of the 7 province ratios")
    f_hi = Fact.derived(f"{hi:.3f}", f"max province ratio ({hi_prov}: "
                        f"{S1_YEAR5[hi_prov][0]}/{S1_YEAR5[hi_prov][1]})")
    f_pool = Fact.derived(f"{pooled_ratio:.3f}", "310/271 owned units per 1,000 (pooled)")
    f_rec = Fact.derived(f"{recent_ratio:.3f}", "115/271 owned units per 1,000 (recent 0-5yr)")

    # SECOND band — the TENURE-anchor axis, which is the DOMINANT uncertainty and
    # is orthogonal to the cross-provincial dispersion the fifth-year band above
    # captures. Computed at year 3 as a concrete alternative anchor, so Task 15's
    # robustness sweep grid (spec §"Run contract") can SEE it rather than only the
    # cross-province spread. year-3 ratio = year-3 recent-immigrant rate / same-
    # province Canadian-born rate (same denominators as the year-5 band).
    ratios3 = {prov: S1_YEAR3[prov] / S1_YEAR5[prov][1] for prov in S1_YEAR5}
    lo3, hi3 = min(ratios3.values()), max(ratios3.values())
    ctr3 = sum(ratios3.values()) / len(ratios3)
    lo3_prov, hi3_prov = min(ratios3, key=ratios3.get), max(ratios3, key=ratios3.get)
    f_lo3 = Fact.derived(f"{lo3:.3f}", f"min year-3 ratio ({lo3_prov})")
    f_ctr3 = Fact.derived(f"{ctr3:.3f}", "unweighted mean of the 7 year-3 province ratios")
    f_hi3 = Fact.derived(f"{hi3:.3f}", f"max year-3 ratio ({hi3_prov})")
    # year-1 band, computed the SAME way as year-3/year-5 (so the fresh-arrival figures the
    # prose cites are DERIVED, never hand-typed): year-1 recent rate / same-province Canadian-born.
    ratios1 = {prov: S1_YEAR1[prov] / S1_YEAR5[prov][1] for prov in S1_YEAR5}
    lo1, hi1 = min(ratios1.values()), max(ratios1.values())
    ctr1 = sum(ratios1.values()) / len(ratios1)
    lo1_prov, hi1_prov = min(ratios1, key=ratios1.get), max(ratios1, key=ratios1.get)
    f_lo1 = Fact.derived(f"{lo1:.3f}", f"min year-1 ratio ({lo1_prov})")
    f_ctr1 = Fact.derived(f"{ctr1:.3f}", "unweighted mean of the 7 year-1 province ratios")
    f_hi1 = Fact.derived(f"{hi1:.3f}", f"max year-1 ratio ({hi1_prov})")
    # The full plausible range spans ALL THREE tenure anchors (year 1/3/5) × geography — the
    # fresh-arrival year-1 floor is the netting-relevant downside, so it must be IN the range.
    combined_lo = min(lo, lo3, lo1)
    combined_hi = max(hi, hi3, hi1)

    note += [
        "## 4. Documented fallback multiplier band (CITED rates -> DERIVED ratio)",
        "",
        f"Basis: **Source 1** — Statistics Canada, catalogue **{SOURCE1['catalogue']}**, "
        f"*{SOURCE1['title']}*, Chart 1 (released {SOURCE1['release']}). "
        f"{SOURCE1['url']}",
        f"  - verbatim: {SOURCE1['quote']}",
        "  - metric: individual homeownership RATE (tax filers 25-54 owning ≥1 residential "
        "property, over that group); population = RECENT immigrants, which matches the "
        "netting's semantic target (arrivals are recent, rental-skewed).",
        "",
        "### 4a. Cited rates and the ratio derived from them",
        "",
        "Fifth year after admission, 2021 (recent-immigrant % / Canadian-born % -> ratio):",
        "",
        "| province | recent immigrant (5yr) | Canadian-born | ratio (derived) |",
        "|---|---:|---:|---:|",
    ]
    for prov, (rec, cdn) in S1_YEAR5.items():
        note.append(f"| {prov} | {rec:.1f}% | {cdn:.1f}% | {rec / cdn:.3f} |")
    note += [
        "",
        f"**Recommended band (rule: min / mean / max of the 7 province ratios, all computed "
        f"from the cited rates):** low **{f_lo}** ({lo_prov}), center **{f_ctr}**, high "
        f"**{f_hi}** ({hi_prov}). The band honestly spans >1.0 (New Brunswick recent immigrants "
        f"OUT-own Canadian-born) — spec:129-131 permits ratio > 1; the multiplier is asserted "
        f"nonnegative-finite, NOT < 1.",
        "",
        "**WHY the fifth year is the anchor (stated, so a stateless Task-15 reader sees it):** "
        "demoflow projects to 2051+, so an arrival cohort's CUMULATIVE owner-household "
        "contribution over the horizon is dominated by its settled-state ownership, not its "
        "first-year rental skew; the fifth-year rate is the closest published proxy for that "
        f"settled state, and year 1 (mean ratio {f_ctr1}) is a first-year-only artifact. This "
        "is a defensible anchor — NOT the only reading (see 4b), and P4 does not rule between "
        "them.",
        "",
        "**WHAT the recommended band's WIDTH measures — READ THIS before using it as a sweep "
        "grid:** its endpoints are cross-PROVINCIAL dispersion at a FIXED tenure (fifth year) — "
        "a SECONDARY axis (whether Alberta differs from New Brunswick, which is not the question "
        "about Montréal). The DOMINANT uncertainty is the TENURE anchor itself, which swings the "
        f"ratio ~{(center - ctr3) / center * 100:.0f}% (year-3 center {f_ctr3} vs year-5 center "
        f"{f_ctr}) and is NOT inside this band. "
        "It is emitted as a SEPARATE machine-readable band in 4b (`DECISION-RATIO-TENURE-"
        "SENSITIVITY`); Task 15's robustness sweep grid must span BOTH axes, not the fifth-year "
        "cross-province spread alone.",
        "",
        "### 4b. The tenure-anchor uncertainty (the DOMINANT axis) + pooled-vs-recent "
        "(recorded, NOT resolved — Task-15 findings)",
        "",
        f"**Source 2** — Statistics Canada, catalogue **{SOURCE2['catalogue']}**, "
        f"*{SOURCE2['title']}* (released {SOURCE2['release']}). {SOURCE2['url']}",
        f"  - verbatim: {SOURCE2['quote']}",
        "",
        f"Pooled ALL-immigrant owned-occupancy ratio = **{f_pool}** (≥ 1: established "
        f"immigrants own at native-or-higher rates), while the RECENT (0-5yr) ratio = "
        f"**{f_rec}**. A pooled ratio would say arrivals add MORE owners than natives and would "
        f"DEFEAT the netting (spec §6: a new rental-skewed immigrant must NOT read as a new "
        f"buyer). The recent-immigrant reading is therefore required. Within the recent "
        f"evidence, earlier tenure is far lower still — year 1 and year 3 province rates:",
        "",
        "| province | year 1 | year 3 | year 5 |",
        "|---|---:|---:|---:|",
    ]
    for prov in S1_YEAR5:
        note.append(f"| {prov} | {S1_YEAR1[prov]:.1f}% | {S1_YEAR3[prov]:.1f}% "
                    f"| {S1_YEAR5[prov][0]:.1f}% |")
    note += [
        "",
        "**The tenure anchor is unresolved — three defensible readings, P4 rules between NONE:**",
        f"  1. FRESH-ARRIVAL: year-1 band [{f_lo1}, {f_ctr1}, {f_hi1}] (min/mean/max of the 7 "
        f"year-1 province ratios), rising toward the 0-5yr per-capita ratio {f_rec}. The §6 "
        "netting target IS the recent-arrival stock, which owns near the year-1 rate before "
        "accumulating tenure, so this reading is squarely in scope; right if p_imm captures "
        "arrival-window ownership.",
        f"  2. SETTLED / long-horizon (year 5): center **{f_ctr}** — right if p_imm captures a "
        "cohort's CUMULATIVE owner demand over a projection to 2051 (see 4a); this is the "
        "RECOMMENDED anchor.",
        f"  3. STOCK-POOLED (all vintages): ratio **{f_pool}** (≥1) — right if p_imm re-applies "
        "to the whole accumulated immigrant household stock; this DEFEATS the netting and is "
        "recorded as the anti-pattern, not a candidate.",
        "",
        f"**Second machine-readable band — the TENURE axis (rule: min/mean/max of the 7 YEAR-3 "
        f"province ratios):** low **{f_lo3}** ({lo3_prov}), center **{f_ctr3}**, high **{f_hi3}** "
        f"({hi3_prov}). Task 15's robustness sweep grid must cover ALL THREE tenure-anchor "
        f"bands (year 1/3/5 — reading #1's year-1 band is the fresh-arrival floor) — the full "
        f"plausible range across the tenure anchor AND geography is roughly "
        f"[{combined_lo:.3f}, {combined_hi:.3f}]. Tranche 2 replaces this coarse ratio with the "
        f"years-since-landing S-curve, which resolves the tenure axis properly. P4 records both "
        f"axes and does NOT calibrate.",
        "",
        "### 4c. borrowed_prior — three transport axes, stated out loud",
        "",
        "- **GEOGRAPHY**: Québec is NOT a covered province in Source 1 (CHSP homeownership "
        "coverage excludes it), so the ROC-province band stands in for the Montréal/Québec "
        "CMAs. Montréal's tenure structure differs materially from the ROC — this is a "
        "genuine borrow, not a formality.",
        "- **METRIC**: Source 1 is INDIVIDUAL residential-property ownership (ages 25-54); the "
        "spec's `p_nonimm` is a household-maintainer tenure propensity (Census). The RATIO is "
        "transported across metric definitions (both groups measured identically within the "
        "source).",
        "- **TENURE-PROFILE**: the fifth-year rate stands in for the full arrival-stock tenure "
        "distribution; §4b records the fresher-cohort pull.",
        "",
        "All three are why the constant lands `borrowed_prior` (spec §6). This is NOT a silent "
        "1.0: it is a cited, banded, published figure with its borrow declared.",
        "",
    ]
    return lo, center, hi, lo3, ctr3, hi3, combined_lo, combined_hi


def main() -> None:
    _FACTS.clear()
    title = [
        "# P4 — Immigrant/non-immigrant ownership ratio (Tranche-1 coarse-netting multiplier)",
        "",
    ]
    body: list[str] = []

    verdict = "UNCONFIRMED-PROBE-FAILED"
    probe_error: str | None = None
    try:
        verdict = _hunt(body)
    except Exception as exc:  # outage OR a vacuous 200 — must NOT launder into a false NOT-FOUND
        probe_error = f"{type(exc).__name__}: {exc}"
        body += [
            "## LIVE HUNT VERDICT: UNCONFIRMED-PROBE-FAILED",
            "",
            f"- `LIVE PROBE FAILED: {probe_error}`",
            "  The WDS did not answer usefully — an outage, or a 200 carrying an empty "
            "population (caught by the floor guard) — so this run cannot AUDIT the not-found "
            "claim. It is deliberately NOT recorded as a confirmed NOT-FOUND (neither an outage "
            "nor a vacuous response may earn one). The fallback band below is external published "
            "literature and stands regardless; re-run against a live service to restore the "
            "§1-§3 audit.",
            "",
        ]

    # The fallback band is network-INDEPENDENT (cited published rates), so it is
    # emitted whether or not the live audit ran.
    lo, center, hi, lo3, ctr3, hi3, comb_lo, comb_hi = _fallback_band(body)

    body += [
        "## DECISION",
        "",
        f"- `DECISION-FOUND-AT-CMA: {'NO' if verdict == 'NOT-FOUND-AT-CMA' else verdict}`",
    ]
    if verdict == "FOUND-CANDIDATE":
        body += [
            "  A cube unexpectedly crossed immigrant × tenure (see §2/§3). This is a "
            "structural surprise, NOT a resolved YES: the cube must be pulled before any "
            "per-CMA ratio is claimed. The fallback band stands only until it is.",
        ]
    body += [
        f"- `DECISION-RATIO-MULTIPLIER-BAND: [{lo:.3f}, {center:.3f}, {hi:.3f}]`  "
        "(low, center, high — the immigrant/non-immigrant ownership ratio for "
        "`p_imm = p_nonimm × ratio`; width = cross-provincial dispersion at the fifth-year "
        "anchor, a SECONDARY axis)",
        f"- `DECISION-RATIO-TENURE-SENSITIVITY: [{lo3:.3f}, {ctr3:.3f}, {hi3:.3f}]`  "
        "(the DOMINANT axis — year-3 tenure anchor; the fresh-arrival year-1 floor is lower "
        "still, see §4b; Task 15's sweep grid must span the full plausible range across the "
        f"year-1/3/5 anchors ≈ [{comb_lo:.3f}, {comb_hi:.3f}])",
        "- `DECISION-RATIO-FLAG: borrowed_prior`",
        f"- `DECISION-RATIO-SOURCE: Statistics Canada, catalogue {SOURCE1['catalogue']} "
        f"(\"{SOURCE1['title']}\"), Chart 1 recent-immigrant vs Canadian-born fifth-year "
        f"homeownership rates by province, 2021; ratio band = min/mean/max across the 7 "
        f"covered provinces`",
        f"- `DECISION-RATIO-CITATION: Statistics Canada. Catalogue {SOURCE1['catalogue']}, "
        f"\"{SOURCE1['title']}\", released {SOURCE1['release']}. {SOURCE1['url']} "
        f"(pooled-vs-recent cross-check: catalogue {SOURCE2['catalogue']}, {SOURCE2['url']})`",
        "",
        "- Standing rule (spec §6): the multiplier is load-bearing; a silent 1.0 is FORBIDDEN "
        "(it would collapse the netting). This probe records a cited, banded, `borrowed_prior` "
        "multiplier — never an invented number and never a bare 1.0. Task 15 lands it in "
        "constants and declares the central value; the CMA cross-tab does not exist free, so "
        "the borrow is mandatory.",
        "",
    ]

    text = "\n".join(title + _provenance_header() + body) + "\n"
    for placeholder in ("[FILL:", "[FILL]", "[FILL "):
        if placeholder in text:
            raise AssertionError(f"run_p4.py emitted an unresolved {placeholder!r} placeholder")
    OUT.write_text(text, encoding="utf-8")
    print(text)


if __name__ == "__main__":
    main()
