"""The GOLDEN-DIFF gate (spec §10) — the committed artifacts, re-derived and compared.

`demoflow/artifacts/{rankings.json,tripwire_baseline.json}` are generated from the committed
data vintage by `scripts/gen_golden.py`, committed, and re-generated here. Everything the run
depends on is PINNED in `demoflow.golden` and imported — the data dir, `now`, the output names —
so this file re-declares no input and a change to the pin cannot pass unnoticed by the gate that
exists to notice changes.

WHAT A RED HERE MEANS IS THE POINT OF THE TASK, not a detail of it. IRCC restates a fraction of
its overlapping cells on every vintage and the ISQ workbooks are re-published, so a golden that
pins computed values WILL red on an upstream refresh with no code change — and a gate whose red
cannot be attributed to data-vs-code teaches its readers to re-mint reflexively, which is the
same as having no gate. So the comparison is made in TWO STEPS, in this order, and each names
its own cause:

  1. PARSED equality — a modeled quantity moved. Read the envelope: `data_vintage.source_hashes`
     moved => the DATA moved; `assumptions_hash` moved => the assumption SELECTION moved; neither
     moved => the CODE moved, which is the only one of the three that is a defect by default.
  2. BYTE equality — the values are identical and the SERIALIZATION moved (indent, key order,
     encoding, line endings). `artifacts._dump_json` pins all four; this is the assertion that
     makes those pins load-bearing.

Nothing is normalized out of either comparison. A golden with holes in its diff has stopped
pinning the thing it was built to pin; `artifacts/README.md` carries the same table for a reader
who meets the files without meeting this test.
"""
import json
import math

import pytest

from demoflow.golden import (
    GOLDEN_ARTIFACTS,
    GOLDEN_DATA_DIR,
    GOLDEN_DIR,
    generate_golden,
)
from demoflow.loaders.ircc import CSV_NAME as IRCC_CSV_NAME
from demoflow.output.tripwires import PR_LANDINGS_INDICATOR, Reason, Status

GOLDEN = GOLDEN_DIR

# THIRD, TEST-OWNED copy of the code-required indicator name list (codex r4-F4): a
# co-deletion must touch code (REQUIRED_INDICATORS) + baseline (golden) + this test in ONE
# PR-visible diff — the residual guard no runtime check can provide. Do NOT "DRY" it away by
# importing `REQUIRED_INDICATORS`: the whole value of this copy is that it is not the same
# object the code and the artifact already share.
_REQUIRED_INDICATOR_NAMES = {
    "pr_landings_annual", "temp_resident_stock", "isq_edition_watch",
    "registre_foncier_volume", "cmhc_senior_sale_5yr", "natural_increase_sign",
}

_REMINT = ("If this is a deliberate refresh, re-mint with `cd demoflow && uv run python "
           "scripts/gen_golden.py` and commit the new bytes — see artifacts/README.md.")


@pytest.fixture(scope="module")
def fresh(tmp_path_factory):
    """ONE re-derivation for the whole module. `generate_golden` runs the ED grid ELEVEN times
    (the central run plus the rank-stability sweep's ten five-axis legs) over five workbooks; a
    per-test run would multiply minutes of real I/O by every assertion below, and this file has
    four."""
    out = tmp_path_factory.mktemp("golden")
    result = generate_golden(out_dir=out)
    # BINDS the golden's name list to what the run actually emitted. A third document added to
    # `run_pipeline` would otherwise be absent from `GOLDEN_ARTIFACTS` — uncommitted, unscanned,
    # and invisible to a gate that only ever looks at names it was handed.
    assert sorted(result["artifacts"]) == sorted(GOLDEN_ARTIFACTS)
    return out


def _committed(name):
    path = GOLDEN / name
    assert path.is_file(), (
        f"the committed golden {path} is MISSING — it is generated by `cd demoflow && uv run "
        f"python scripts/gen_golden.py` and committed alongside the code that produces it")
    return path


def _match_golden(fresh_dir, name) -> dict:
    """Parsed equality, then byte equality — each with its own attribution (see the module
    docstring). Returns the committed document."""
    committed_bytes = _committed(name).read_bytes()
    fresh_bytes = (fresh_dir / name).read_bytes()
    committed_doc = json.loads(committed_bytes)
    fresh_doc = json.loads(fresh_bytes)

    if fresh_doc != committed_doc:
        cause = ("the DATA moved (data_vintage.source_hashes differs)"
                 if fresh_doc.get("data_vintage") != committed_doc.get("data_vintage") else
                 "the assumption SELECTION moved (assumptions_hash differs)"
                 if fresh_doc.get("assumptions_hash") != committed_doc.get("assumptions_hash")
                 else "the CODE moved — the envelope is IDENTICAL, so this is a model change, "
                      "not an upstream refresh")
        pytest.fail(f"{name}: a modeled quantity moved — {cause}. {_REMINT}")

    assert fresh_bytes == committed_bytes, (
        f"{name}: every VALUE is identical and the SERIALIZATION moved — indent, key order, "
        f"encoding or line endings, all of which artifacts._dump_json pins. {_REMINT}")
    return committed_doc


def test_rankings_match_golden(fresh):
    _match_golden(fresh, "rankings.json")


def test_tripwire_baseline_matches_golden(fresh):
    committed = _match_golden(fresh, "tripwire_baseline.json")
    inds = {t["indicator"] for t in committed["indicators"]}
    assert _REQUIRED_INDICATOR_NAMES <= inds       # literal name list pinned here (third copy)


def test_golden_is_strict_json_no_nan():
    """The golden parses to a FINITE tree — checked on the READ side, over both files.

    The obvious form of this test is a substring scan for "NaN"/"Infinity" in the text, and it
    is weaker than it looks in both directions: it MISSES `1e999`, which is legal JSON grammar
    that `json.loads` overflows to `inf`, and it false-REDS on any legitimate string that
    happens to contain those letters. `parse_constant` alone closes only the first half of the
    first gap — it fires on the three literal tokens and never sees `1e999` either — so the
    hook and a finiteness walk are BOTH required. `artifacts.write_json_strict` already refuses
    a non-finite tree on the write side; this is the independent check that the committed bytes
    are what that writer claims, made against the file rather than against the writer.
    """
    for name in GOLDEN_ARTIFACTS:
        text = _committed(name).read_text(encoding="utf-8")
        doc = json.loads(text, parse_constant=_refuse_json_constant)
        _assert_parsed_finite(doc, name)


def test_golden_declares_the_absent_ircc_feed(fresh):
    """The golden's IRCC state is DECLARED, not ambient (and it is the honest committed one).

    `data/ircc_pr_by_cma.csv` is deliberately NOT committed — committing it would flip
    `pr_landings_annual` from structurally UNKNOWN to a live verdict — so the golden pins
    UNKNOWN / `source_unavailable` and an envelope with no IRCC key. That makes the golden
    environment-dependent in a way no other input is: drop the feed into `data/` and the two
    diff tests above red with no code change, and the golden then fails in any checkout WITHOUT
    the file. This test is that dependency made NAMED, so the day it happens a reader gets the
    cause instead of an opaque byte diff — and the answer is a re-mint, never a fixture.
    """
    feed = GOLDEN_DATA_DIR / IRCC_CSV_NAME
    committed = json.loads(_committed("tripwire_baseline.json").read_text(encoding="utf-8"))
    landed = (f"{feed} EXISTS. The IRCC feed landed — the golden must be RE-MINTED, which is "
              f"success, not a regression. {_REMINT}")

    assert not feed.exists(), landed
    assert IRCC_CSV_NAME not in committed["data_vintage"]["source_hashes"], (
        f"the golden's envelope declares {IRCC_CSV_NAME}, so it was minted over a vintage that "
        f"HAD the feed while this checkout does not. {_REMINT}")
    (record,) = [r for r in committed["indicators"] if r["indicator"] == PR_LANDINGS_INDICATOR]
    assert (record["status"], record.get("reason")) == (
        Status.UNKNOWN.value, Reason.SOURCE_UNAVAILABLE.value), landed


# ------------------------------------------------------------------ strict-JSON read side

class _NonFiniteJSON(ValueError):
    """A golden that parses to something outside the finite reals."""


def _refuse_json_constant(token):
    raise _NonFiniteJSON(f"the golden carries the JSON constant {token!r}")


def _assert_parsed_finite(node, where) -> None:
    if isinstance(node, float):
        assert math.isfinite(node), (
            f"{where} parses to the non-finite float {node!r} — legal JSON grammar (e.g. "
            f"1e999) that `allow_nan=False` does not stop on the way out")
    elif isinstance(node, dict):
        for key, value in node.items():
            _assert_parsed_finite(value, f"{where}.{key}")
    elif isinstance(node, list):
        for index, value in enumerate(node):
            _assert_parsed_finite(value, f"{where}[{index}]")
